version: '3.8'

services:
  # Только сборка Docker-образа приложения
  bukhindor-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: bukhindor-api:latest
    ports:
      - "8080:8080"
      - "9091:9091"